"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./styles/globals.css";
import { Toaster } from "react-hot-toast";
import { Raleway } from "next/font/google";

// export const metadata = {
//   title: "Weather Webapp",
//   description: "Generated by Hamidreza",
// };

const raleway = Raleway({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-raleway",
});

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <QueryClientProvider client={queryClient}>
          <Toaster />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
