"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./styles/globals.css";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";

// export const metadata = {
//   title: "Weather Webapp",
//   description: "Generated by Hamidreza",
// };

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <QueryClientProvider client={queryClient}>
          <Toaster />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
