"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./styles/globals.css";
import { Toaster } from "react-hot-toast";

// export const metadata = {
//   title: "Weather Webapp",
//   description: "Generated by Hamidreza",
// };

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <Toaster />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
